### ISSUE TITLE
Dropdown component does not set initial value

### ISSUE THREAD

**Issue by K1vs** [ThatOpen/engine_ui-components#24]
### Describe the bug 📝

I expect, dropdown should have initial value if it has option with "checked" attribute.

### Steps to reproduce 🔢

1. Open demo page https://thatopen.github.io/engine_ui-components/examples/Dropdown/
![image](https://github.com/ThatOpen/engine_ui-components/assets/11088116/94ca872a-54d3-4803-9954-ee0ee3b8ff03)
2. Actual - Dropdown has empty selected value; Expected - Dropdown has IfcWindow value (because this option marked as checked) 
![image](https://github.com/ThatOpen/engine_ui-components/assets/11088116/399f34fb-a030-4fb8-8ca9-9516545fdd1b)
3. Try open and close dropdown - after this dropdown works as expected.
![image](https://github.com/ThatOpen/engine_ui-components/assets/11088116/eaadc6bb-bd83-4d10-87b6-bb7a9f43eb62)

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 15.84 GB / 31.79 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.68)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Fixed on @thatopen/ui@2.1.1! Closing issue.
