### ISSUE TITLE
Provide a UI component for the html textarea

### ISSUE THREAD

**Issue by avirads** [ThatOpen/engine_ui-components#26]
### Description 📝

When sending a note or comment using a webhook, it would be useful to have a textarea instead of a text field. 

### Suggested solution 💡

Please add it into the bim ui components list for component completeness. 

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Hey @avirads! This has been implemented since @thaopen/components@2.1.4. You can write the following:

`<bim-text-input label="Description" type="area"></bim-text-input>`
