### ISSUE TITLE
onClick event bim-button React

### ISSUE THREAD

**Issue by mokmail** [ThatOpen/engine_ui-components#27]
### Describe the bug 📝

the onclick ebvent of the bim-button component when setting up a react app is not workek as expected , other frame works seem not to be affected 

### System Info 💻

```shell
npm create vite . 
// select React 
// select Javascript
npm install @thatopen/ui
npm run dev
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [ ] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [ ] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [ ] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hey @mokmail! This has been fixed in @thatopen/ui@2.1.3. Closing this!
