### ISSUE TITLE
BUI Component stick on screen

### ISSUE THREAD

**Issue by CindySim08** [ThatOpen/engine_ui-components#38]
### Describe the bug 📝

Im facing this issue where the BUI Component stays on the screen even after I navigate to a different page.

![BUI Component](https://github.com/user-attachments/assets/ba04103a-b8e7-4334-bd88-baf0bd311ff1)

`  useEffect(() => {
    if (typeof window === "undefined" || !containerRef.current) return;

    //setup 3D environment 

    (async () => {
      BUI.Manager.init();
      const panel = BUI.Component.create(() => {
        return BUI.html`
          <bim-toolbar-section 
            active 
            style="position: fixed; bottom: 0; left: 50%; transform: translateX(-50%);"
          >
           <bim-toolbar-section 
            style="display: flex; justify-content: center;"
          >
            <bim-button
            label="Upload IFC"
            icon="mage:box-3d-fill"
            ></bim-button>
           </bim-panel-section>
          </bim-toolbar-section>
        `;
      });      
      document.body.append(panel);

      fragments.onFragmentsLoaded.add((model) => {
      });
    })();

    return () => {
      components.dispose();
    };
  }, []);`

### System Info 💻

```shell
Browsers:
    Edge (126.0.2592.113)
    Firefox (126.0)
    Chrome (127.0.6533.72)
```

### Used Package Manager 📦

yarn

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HoyosJuan** [comment]
Hey @CindySim08! do you still have this issue? I couldn't reproduce it.

**Comment by CindySim08** [comment]
Unfortunately, I no longer have any active involvement with BIM-related projects. The library's constant changes and the extended time it took to receive a response made it challenging to move forward, so I’ve since shifted my focus to other technologies.
