### ISSUE TITLE
Model List - buttons

### ISSUE THREAD

**Issue by matilde-mantoan-efm** [ThatOpen/engine_ui-components#39]
### Description 📝

Hi! I am using the Models List component, could you add a way to remove/disable the delete button?

![image](https://github.com/user-attachments/assets/a6708a60-793a-4b7c-b450-2bf53407c44d)

Thank you! 

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Hey @matilde-mantoan-efm! This has been implemented in @thatopen/ui-obc@2.1.5. Just take a look at [this](https://github.com/ThatOpen/engine_ui-components/blob/main/packages/obc/src/components/tables/ModelsList/example.ts#L62).

**Comment by matilde-mantoan-efm** [comment]
Thank you!!!
