### ISSUE TITLE
Use of htmx 

### ISSUE THREAD

**Issue by j209** [ThatOpen/engine_ui-components#47]
### Description 📝

Can i use [Htmx](https://github.com/bigskysoftware/htmx) in these libraries?

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that requests the same feature to avoid creating a duplicate.

**Comment by HoyosJuan** [comment]
Hey @j209, I haven't used HTMX before but you should be able, as it provides with a set of attributes you can use in any HTMLElement, and this is a Web Components library.
