### ISSUE TITLE
Table can not build, about obc module,ElementProperties, XXX.loadData

### ISSUE THREAD

**Issue by fc88804DOTcn** [ThatOpen/engine_ui-components#52]
### Describe the bug 📝

Hello, first of all, thank you for reading. 
I am currently testing the OBC functionalities such as ElementProperties,
 but I have encountered an error that prevents my code from continuing execution. 
The error message is "XXX.loadData is not a function". This error is triggered by the following line of code:  
  
const [propertiesTable, updatePropertiesTable] = CUI.tables.elementProperties({  
  components,  
  fragmentIdMap: {},  
});  
  
I noticed that unlike other tutorials,
 this one does not have an import statement like "import * as * from "**" at the beginning. 
However, in the first four lines of https://github.com/ThatOpen/engine_ui-components/blob/main/packages/obc/src/components/tables/ElementProperties/example.ts, 
I found the crucial code "import * as CUI from "../..", which seems to be the missing piece.  

Here comes the problem. 
I saw that it imports everything from the parent directory's parent directory. 
When I copied the 'tables' folder into my project, I encountered the error "loadData is not a function".

Then i went through the code line by line but still couldn't figure out where the mistake was.

 However, I find the OBC module, so I installed @thatopen/ui-obc on npm, 
but the error appeared again, "loadData is not a function."

 God, please, save me. I'm just a beginner trying to follow a tutorials. Thanks again.

![图片](https://github.com/user-attachments/assets/02e039ff-1339-4fe3-a232-ab41ce7aa4b0)
![图片](https://github.com/user-attachments/assets/d7d6a88e-46eb-463b-a097-48aee16ac364)

![图片](https://github.com/user-attachments/assets/e22a82d5-8592-4107-bd7a-ad28cc630aef)
![图片](https://github.com/user-attachments/assets/6e8d62f7-60d1-423f-9108-991ebe0012db)

### Reproduction ▶️

https://github.com/fc88804DOTcn/thatopen-ifc-learn.git

### Steps to reproduce 🔢

https://github.com/fc88804DOTcn/thatopen-ifc-learn.git

### System Info 💻

```shell
Win10 LTSC 2019/node22 / firefox 130.0.1
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hustodemon** [comment]
@fc88804DOTcn  I'm hitting the same problem. I've installed the `@thatopen/ui-obc` with `npm install`. How did you resolve the issue?
